name: K6 Performance Tests

on:
  push:
    branches:
      - main

jobs:
  performance-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates
          sudo apt-get install -y unzip
          curl -L -o k6.tar.gz https://github.com/loadimpact/k6/releases/download/v0.34.1/k6-v0.34.1-linux-amd64.tar.gz
          tar xf k6.tar.gz
          ls -la
          ls -la k6*

      - name: Run Performance Tests
        run: ./k6 run getPosts.js

      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        with:
          name: k6-test-results
          path: summary.html
